.TH UMESS 1 "March 14, 2022" ""
.SH NAME
umess \- a simple X pop-up 
.SH SYNOPSIS
\fBumess\fP 
[ \fB\-{b|t}{l|r}\fP ]
[ \fB\-f\fP \fIfont\fP ] 
[ \fB\-F\fP \fIforeground-color\fP ] 
[ \fB\-B\fP \fIbackground-color\fP ] 
[ \fB\-m\fP \fImonitor-name\fP ]
[ \fB\-d\fP ]
[ \fB\-h\fP ]
.SH DESCRIPTION
.B umess
spawns a small window with given text and dimensions adjusted to its contents.
It stays until input stream persists, unless \fB\-d\fP option is enabled.
It can be used for showing such data as current time or battery charge with the
help of some hotkey daemon such as \fBxbindkeys\fP or \fBsxhkd\fP or for simple
notifications.
.SH OPTIONS
.TP
.B \-{b|t}|{l|p}
Specify vertical (\fBb\fPottom or \fBt\fPop) and horizontal
(\fBl\fPeft or \fBr\fPight) position of the window. 
With no value provided the window appears in the middle of the screen.
.TP
.B \-d
Die on the left mouse button click.
Usefull for important and urgent notifications.
.TP
.B \-h
Print the synopsis and exit.
.TP
.B \-f \fIfont\fP
Specify text font. It should be provided in the Xft notation.
.TP
.B \-F|B \fIforeground-color|background-color\fP
Specify text and window background colors. 
Hex color codes and X color names are supported.
Keep in mind that hash symbol is reserved in shell, so hex color codes should
be enclosed in quotes.
.TP
.B \-m \fImonitor-name\fP
Specify monitor on which the window will be displayed. 
By default the monitor pointed by the mouse coursor is used.
.SH AUTHOR
Vasily Negrebetskiy <kmiziz.com at gmail\&.com>
